INSERT INTO `recetas` (`id`, `tipo`, `nombre`) VALUES
(01, 'Entrantes', 'Tabla de Nachos'),
(02, 'Entrantes', 'Empanadillas De Atun'),
(03, 'Entrantes', 'Huevos Rellenos'),
(04, 'Entrantes', 'Tostas de Salmon'),
(05, 'Entrantes', 'Empanadillas Chinas'),
(06, 'Platos', 'Pollo Teriyaki'),
(07, 'Platos', 'Filetes Rellenos'),
(08, 'Platos', 'Arroz Frito'),
(09, 'Platos', 'Tortilla de Patata'),
(10, 'Platos', 'Pasta Carbonara'),
(11, 'Postres', 'Tarta de Limon'),
(12, 'Postres', 'Tarta de Naranja'),
(13, 'Postres', 'Helado de Platano'),
(14, 'Postres', 'Proximamente'),
(15, 'Postres', 'Proximamente');